### ISSUE TITLE
Cannot run ./05_run_fits.sh because of mismatch dimmension

### ISSUE THREAD

**Issue by haithanhp** [classner/generating_people#4]
Hi @classner ,

When I load the model "basicModel_neutral_lbs_10_207_0_v1.0.0.pkl"  and 'regressors_locked_normalized_hybrid.npz'  in ~/git/up/models/3D directory, I notice that the dimension of betas is 10 + 1 =11, while _REGRESSOR is input with the dimension of 301x20. This leads to mismatch the dimension in the following codes in **capsule_man.py** line 132 - 136:
 
pad = ch.concatenate((wrt_betas, ch.zeros(n_shape_dofs-len(wrt_betas)), ch.ones(1)))
lengths = pad.dot(length_regs)
rads = pad.dot(rad_regs)

Could you explain what is the meaning of **10** and **301x20**?

Best,
Hai

**Comment by classner** [comment]
Hi @HaiPhan1991,

thanks a lot for reporting this! It was a simple dimension mismatch w.r.t. the number of shape parameters we used. I changed this a while ago and didn't rerun fits with body shape since then. The code is now updated; if you get the `up` master it will just work (I project the regressors right after loading).

Best,
Christoph
