### ISSUE TITLE
where to download the tf-record data

### ISSUE THREAD

**Issue by dashan336** [classner/generating_people#8]
I am getting this error:
Exception: /home/drive/generate_people/generating_people-master/generation/data/people/full contains no files for this mode

I saw you've already answered this question .But I'm still confused where to download the tf-record data. Could you please answer my question ?

**Comment by classner** [comment]
Sorry, the tfrecords themselves are not available for download. Please follow this section in the README:

Otherwise, download the pre-processed data from our website (http://files.is.tuebingen.mpg.de/classner/gp/), unzip it to the folder generation/data/pose/extracted and only run the last script
./09_pack_db.sh full
